### PR TITLE
[FIXED-#2082] Fixes sparse chaining algorithm.

### LINKED ISSUE #2082: Unexpected results with chainSeedsGlobally
In this scenario:
```

   /
  / /
   /
  /

 Y
 |
  ---> X
```

seed1 has length 3 and seed2 has length 2.  `chainSeedsGlobally` returns seed2, which is not the `optimal` solution.

This is the test case I added to `tests/seeds/test_seeds_global_chaining.cpp`:

```cpp
    {
        TSeedSet seedSet;

        addSeed(seedSet, TSeed(0, 0, 3), Single());
        addSeed(seedSet, TSeed(2, 3, 2), Single());

        TSeedChain result;
        chainSeedsGlobally(result, seedSet, SparseChaining());

        SEQAN_ASSERT_EQ(1u, length(result));
        SEQAN_ASSERT_EQ(TSeed(0, 0, 3), result[0]); /* fails, returns TSeed(2, 3, 2) */
    }
```

An extreme case:
```cpp
    {
        TSeedSet seedSet;

        addSeed(seedSet, TSeed(0, 0, 100), Single());
        addSeed(seedSet, TSeed(95, 95, 10), Single());

        TSeedChain result;
        chainSeedsGlobally(result, seedSet, SparseChaining());

        SEQAN_ASSERT_EQ(1u, length(result));
        SEQAN_ASSERT_EQ(TSeed(0, 0, 100), result[0]); /* fails, returns TSeed(95, 95, 10) */
    }
```

From what I can see in <em>Gusfield 1997</em>, the algorithm does not cover this case. The algorithm only discards solutions which are "higher up", and the author states that in the list `L` the last entry (i.e. the highest rectangle) contains the best score, which is not the case here. That could explain the unexpected output of `chainSeedsGlobally`. Maybe I am missing something?

### PR DESCRIPTION
**Pull request by rrahn**
fixes #2082

### CODE REVIEW

File: include/seqan/seeds/seeds_global_chaining.h [hunk 1]
```diff
@@ -153,98 +177,108 @@ chainSeedsGlobally(
...
-                    itJ = intermediateSolutions.end();
-                    --itJ;
-                } else {
-                    continue;
-                }
-            } else {
-                SEQAN_ASSERT_GT(intermediateSolutions.size(), 0u);  // TODO(holtgrew): Remove this assertion?
-                --itJ;
+            TIntermediateSolution referenceSolution(beginPositionV(seed_k), std::numeric_limits<TSize>::max(), std::numeric_limits<unsigned>::max());
+            // std::cout << "    intermediateSolutions.upper_bound(" << beginPositionV(seed_k) << ")" << std::endl;
```
Comment (h-2) [inline include/seqan/seeds/seeds_global_chaining.h]: remove debug or mark clearly as such, e.g. by
```cpp
#if 0 // DEBUG functionality
    std::cout << "    intermediateSolutions.upper_bound(" << beginPositionV(seed_k) << ")" << std::endl;
#endif
```

Comment (rrahn) [reply include/seqan/seeds/seeds_global_chaining.h]: This is untouched code. Just moved around by git a little.
