### PR TITLE
[HOTFIX] Change Version Check Option to bool and manage messages via macros.

### LINKED ISSUE #1980: Nightly Master/Develop Tests fail on Win 32/64
There seems to be a sporadic issue, when develop and master builds are executed in parallel on windows.
I assign this at the moment to @smehringer, since it might be related to the version checker, since this is involved on develop and master.

### PR DESCRIPTION
**Pull request by smehringer**
This includes the following changes:
- the version-check option is now a bool and can be turned off/on by specifying off/on/yes/no/1/0...
- The server is only once asked for the current versions of both app and library (result is stored in one app.version file. This might fix #1980 since it could be cause by file handling conflicts of the seqan.version file)
- The command line messages were restricted in the following way:
   - app users will not be notified of new library versions, nor whether the app is not registered
   - app developers (DEBUG mode) will not be notified about "new app versions" they are working on, but only on new library versions and whether they want to register their app to priovide easy version updates for their users

### CODE REVIEW

File: include/seqan/arg_parse/arg_parse_version_check.h [hunk 1]
```diff
@@ -368,26 +368,33 @@ inline String<int> _getNumbersFromString(std::string const & str)
...
+
+#if !defined(NDEBUG) || defined(SEQAN_TEST_VERSION_CHECK_)
+        if (app_version == VersionControlTags_<>::UNREGISTERED_APP)
             me.errorStream << VersionControlTags_<>::MESSAGE_UNREGISTERED_APP;
-            line.clear();
-        }
+#endif // !defined(NDEBUG) || defined(SEQAN_TEST_VERSION_CHECK_)
+
+        if (std::regex_match(app_version, std::regex("^[[:digit:]]+\\.[[:digit:]]+\\.[[:digit:]]+$")))
+            versions[0] = app_version;
```
Comment (rrahn) [inline include/seqan/arg_parse/arg_parse_version_check.h]: this can be put into the debug mode section

File: include/seqan/arg_parse/arg_parse_version_check.h [hunk 2]
```diff
@@ -436,24 +443,34 @@ inline void _checkForNewerVersion(VersionCheck & me, std::promise<bool> prom)
         return;
     }
 
-    std::string str_server_version(_readVersionString(me, version_filename));
-    if (!str_server_version.empty())
+    std::vector<std::string> str_server_versions{"", ""};
+    _readVersionStrings(str_server_versions, me, version_filename);
+
+#if !defined(NDEBUG) || defined(SEQAN_TEST_VERSION_CHECK_) // only check seqan version in debug or testing mode
+    if (!str_server_versions[1].empty()) // seqan version
```
Comment (rrahn) [inline include/seqan/arg_parse/arg_parse_version_check.h]: also check if unregisted app and notify, otherwise just check seqan version.

File: include/seqan/arg_parse/arg_parse_version_check.h [hunk 3]
```diff
@@ -139,7 +139,7 @@ struct VersionCheck
         {
             _version = versionMatch.str(1); // in case the git revision number is given take only version number
         }
-        _url = static_cast<std::string>("http://seqan-update.informatik.uni-tuebingen.de/check/SeqAn_") + _getOS() + _getBitSys() + _name + "_" + _version;
+        _url = static_cast<std::string>("http://www.seqan.de/version_check/SeqAn_") + _getOS() + _getBitSys() + _name + "_" + _version;
```
Comment (smehringer) [inline include/seqan/arg_parse/arg_parse_version_check.h]: This was only for testing purposes.

File: include/seqan/arg_parse/arg_parse_parse.h [hunk 4]
```diff
@@ -310,28 +310,17 @@ ArgumentParser::ParseResult parse(ArgumentParser & me,
 
 #ifndef SEQAN_DISABLE_VERSION_CHECK
     // do version check if not turned off by the user
-    std::string version_option;
-    getOptionValue(version_option, me, "version-check");
+    bool check_version;
```
Comment (smehringer) [inline include/seqan/arg_parse/arg_parse_parse.h]: yes
