### PR TITLE
[FIX] Fixes bug in chainSeedsGlobally().

### LINKED ISSUE #2318: chainSeedsGlobally assert
Hi, 
  I'm using chainSeedsGlobally to filter alignments.  Does the sdp implementation require that the start and end points of seeds be on the same diagonal? There are no issues when all seeds are diagonal, but   the following code asserts:

```terminal
./test.out 
seqan/include/seqan/seeds/seeds_global_chaining.h:281 Assertion failed : _checkScoreInvariant(intermediateSolutions) should be true but was 0

stack trace:
  0          [0x401860]  ./test.out()
  1          [0x402a88]  ./test.out()
  2          [0x4015ca]  ./test.out()
  3    [0x7f1bd60c2c05]  __libc_start_main + 0xf5
  4          [0x4013c9]  ./test.out()
```

```c++
#include <vector>
#include <iostream>
#include "seqan/seeds.h"
#include "seqan/align.h"

using namespace std;
int main() {

	seqan::SeedSet<seqan::Seed<seqan::Simple>, seqan::Unordered> simple;
	seqan::addSeed(simple, seqan::Seed<seqan::Simple>(1,  5, 10, 15), seqan::Single());
	seqan::addSeed(simple, seqan::Seed<seqan::Simple>(5,  9, 40, 34), seqan::Single());
	seqan::addSeed(simple, seqan::Seed<seqan::Simple>(40, 10, 45, 17), seqan::Single());

	seqan::String<seqan::Seed<seqan::Simple> > simpleChain;
	seqan::chainSeedsGlobally(simpleChain, simple, seqan::SparseChaining());
	cout << "Simple chain " << seqan::length(simpleChain) << endl;
}
```

### PR DESCRIPTION
**Pull request by smehringer**
This fixes #2318 

The if-clause was ill-formed and not consistent with the original Gusfield algorithm. The minimal example that caused the assert in the referenced issue was included as a test case.

### CODE REVIEW

**Comment by smehringer** [comment]
@cpockrandt please review so we can merge :)

**Comment by cpockrandt** [comment]
I think I reviewed this PR verbally already :thinking: :grin: 

Besides naming of the test case `_example`, it lgtm

File: tests/seeds/test_seeds_global_chaining.cpp [hunk 1]
```diff
@@ -142,6 +142,16 @@ SEQAN_DEFINE_TEST(test_seeds_global_chaining_sparse_length)
         SEQAN_ASSERT_EQ(1u, length(result));
         SEQAN_ASSERT_EQ(TSeed(0, 0, 100), result[0]);
     }
+
+   { // Issue #2318
+        SeedSet<Seed<Simple>, Unordered> simple;
```
Comment (cpockrandt) [inline tests/seeds/test_seeds_global_chaining.cpp]: Why not use TSeedSet, TSeed and TSeedChain? :stuck_out_tongue_winking_eye:

File: include/seqan/seeds/seeds_global_chaining.h [hunk 2]
```diff
@@ -232,51 +242,41 @@ chainSeedsGlobally(
...
-                TIntermediateSolution sol(endPositionV(seed_k), qualityOfChainEndingIn[it_k->i3], it_k->i3);
-                // std::cout << "  INSERT (" << sol.i1 << ", " << sol.i2 << ", " << sol.i3 << ") " << __LINE__ << std::endl;
-                intermediateSolutions.insert(sol);
+                TIntermediateSolutionsIterator ptr = itDel;
+                ++itDel;
+                if (qualityOfChainEndingIn[it_k->i3] > ptr->i2)
+                {
+                    // std::cout << "  ERASE (" << ptr->i1 << ", " << ptr->i2 << ", " << ptr->i3 << ")" << std::endl;
+                    intermediateSolutions.erase(ptr);
+                }
```
Comment (marehr) [inline include/seqan/seeds/seeds_global_chaining.h]: you must break here if this condition is false, because the condition will stay false for all following iterations

otherwise you might not achieve the `r log r` time

**Comment by smehringer** [comment]
@marehr @cpockrandt  Can you take a final look?

File: include/seqan/seeds/seeds_global_chaining.h [hunk 3]
```diff
@@ -138,8 +138,14 @@ chainSeedsGlobally(
...
-    resize(seeds, length(seedSet));
-    std::copy(seedSet._seeds.begin(), seedSet._seeds.end(), begin(seeds, Standard()));
+    reserve(seeds, length(seedSet));
+    for (auto const & seed : seedSet._seeds)
+    {
+        SEQAN_ASSERT_LT(beginPositionH(seed), endPositionH(seed)); // [beginH, endH) must be at least of length 1
+        SEQAN_ASSERT_LT(beginPositionV(seed), endPositionV(seed)); // [beginV, endV) must be at least of length 1
+        appendValue(seeds, seed);
+    }
+    // std::copy(seedSet._seeds.begin(), seedSet._seeds.end(), begin(seeds, Standard()));
```
Comment (smehringer) [inline include/seqan/seeds/seeds_global_chaining.h]: remove

File: include/seqan/seeds/seeds_global_chaining.h [hunk 4]
```diff
@@ -196,7 +196,11 @@ chainSeedsGlobally(
         // The seed belonging ot the interval point is seed k.
         TSeed const & seed_k = seeds[it_k->i3];
 
-        // std::cout << "Processing interval point (" << it->i1 << ", " << it->i2 << ", " << it->i3 << ")" << std::endl;
+        // std::cout << "Processing interval point (" << it_k->i1 << ", " << it_k->i2 << ", " << it_k->i3 << ")" /*<< std::endl*/;
```
Comment (smehringer) [inline include/seqan/seeds/seeds_global_chaining.h]: remove couts

File: include/seqan/seeds/seeds_global_chaining.h [hunk 5]
```diff
@@ -238,50 +242,41 @@ chainSeedsGlobally(
...
-                intermediateSolutions.insert(sol);
+                TIntermediateSolutionsIterator ptr = itDel;
+                ++itDel;
+                if (qualityOfChainEndingIn[it_k->i3] > ptr->i2)
+                {
+                    // std::cout << "  ERASE (" << ptr->i1 << ", " << ptr->i2 << ", " << ptr->i3 << ")" << std::endl;
+                    intermediateSolutions.erase(ptr);
+                }
             }
+
```
Comment (smehringer) [inline include/seqan/seeds/seeds_global_chaining.h]: remove
