### PR TITLE
[FIX] Added length function for const dependent-generous-stringset.

### LINKED ISSUE #1939: No length() function for const string set dependent generous?
The `length()` function is overloaded by the dependent generous string set ([here](https://github.com/seqan/seqan/blob/master/include/seqan/sequence/string_set_dependent_generous.h#L185)) but only for **non const** string sets. Is this intentionally?

(same applies for `getValueById()`)

### PR DESCRIPTION
**Pull request by smehringer**
Fixes #1939

### CODE REVIEW

File: include/seqan/sequence/string_set_dependent_generous.h [hunk 1]
```diff
@@ -187,6 +187,13 @@ length(StringSet<TString, Dependent<Generous> > & me)
     return length(me.limits) - 1;
 }
 
+template <typename TString >
```
Comment (rrahn) [inline include/seqan/sequence/string_set_dependent_generous.h]: please remove the last space in the ```<>```
