### PR TITLE
[FIX] Tutorials - Removed all hardcoded code-block elements

### LINKED ISSUE #858: Move all cpp code blocks from the manual into files
Many tutorials contain cpp code blocks (directive .. code-block:: cpp) rather than external compilable files (directive .. includefrags:: file.cpp).

Such code blocks are not built in nightly/ci and potentially broken.

See e.g. https://github.com/seqan/seqan/blob/master/manual/source/Tutorial/Indices.rst#assignment-1 or https://github.com/seqan/seqan/blob/master/manual/source/Tutorial/Sequences.rst.

### PR DESCRIPTION
**Pull request by smehringer**
See master PR #1416.
Fixes #858.

### CODE REVIEW

File: demos/tutorial/a_first_example/example_tags_for_print.cpp [hunk 1]
```diff
@@ -0,0 +1,42 @@
...
+    }
+
+    for (unsigned i = 0; i < seqan::length(output); ++i)
+        std::cout << output[i] << " ";
+    std::cout << std::endl;
+}
+
+int main(){
+    return 0;
+}
```
Comment (h-2) [inline demos/tutorial/a_first_example/example_tags_for_print.cpp]: Please make sure all files end with a newline!

File: demos/tutorial/a_first_example/example_tags_for_print.cpp [hunk 2]
```diff
@@ -0,0 +1,42 @@
...
+        }
+    }
+
+    for (unsigned i = 0; i < seqan::length(output); ++i)
+        std::cout << output[i] << " ";
+    std::cout << std::endl;
+}
+
+int main(){
+    return 0;
```
Comment (h-2) [inline demos/tutorial/a_first_example/example_tags_for_print.cpp]: please always put the { on a newline

File: demos/tutorial/alphabets/example_bitsPerValue.cpp [hunk 3]
```diff
@@ -0,0 +1,16 @@
+#include <iostream>
+#include <seqan/basic.h>
+
+using namespace seqan;
+
+int main(){
+
+	typedef Dna TAlphabet;
```
Comment (h-2) [inline demos/tutorial/alphabets/example_bitsPerValue.cpp]: please indent always with four spaces, never with tabs or eight spaces!

File: demos/tutorial/alphabets/example_ordValue.cpp [hunk 4]
```diff
@@ -0,0 +1,21 @@
+#include <iostream>
+#include <seqan/basic.h>
+
+using namespace seqan;
+
+int main(){
+
+//![main]
+Dna a = 'A';
+Dna c = 'C';
```
Comment (h-2) [inline demos/tutorial/alphabets/example_ordValue.cpp]: please indent properly!

File: demos/tutorial/seed_and_extend/example2.cpp [hunk 5]
```diff
@@ -22,7 +22,7 @@ int main()
                           endPositionV(seed)) << "\n";
 
     // Perform match extension.
-    extendSeed(seed, seqH, seqV, EXTEND_LEFT, MatchExtend());
+    extendSeed(seed, seqH, seqV, EXTEND_BOTH, MatchExtend());
     // Print the resulting seed.
```
Comment (h-2) [inline demos/tutorial/seed_and_extend/example2.cpp]: why this change?

**Comment by h-2** [comment]
@smehringer I know a lot of the code didnt conform to our guideline before, but when touching it, please make sure that it does. All the issues above appear multiple time, i.e. please make sure that opening braces start on a new line, that everything is correctly indented and the every file ends in an empty newline! Thanks :smile:

File: demos/tutorial/seed_and_extend/example2.cpp (hunk 5 above)
Comment (smehringer) [inline demos/tutorial/seed_and_extend/example2.cpp]: Because the tutorial states: "In the most simple case we simply look for matching characters in both sequences to the left and right end of the seed."
http://seqan.readthedocs.org/en/master/Tutorial/SeedAndExtend.html (Seed Extension)
I just wanted to make it consistent. Do you want me to change it back?

File: demos/tutorial/alphabets/example_ordValue.cpp (hunk 4 above)
Comment (smehringer) [inline demos/tutorial/alphabets/example_ordValue.cpp]: The Tutorial Webpages often do not include the main function, thus the (correct) indentation will occur "without a reason" for the person who is just looking at the webpage and not the file. 
But I assume a consistent code style is more important than a slight change of the look on the Webpage?

File: demos/tutorial/seed_and_extend/example2.cpp (hunk 5 above)
Comment (h-2) [inline demos/tutorial/seed_and_extend/example2.cpp]: > I just wanted to make it consistent. Do you want me to change it back?

No, I justed wanted to know, good change :+1:

File: demos/tutorial/alphabets/example_ordValue.cpp (hunk 4 above)
Comment (h-2) [inline demos/tutorial/alphabets/example_ordValue.cpp]: Yeah, I think four spaces indention are not a problem for readability.

File: demos/tutorial/bed_io/base.cpp [hunk 6]
```diff
@@ -0,0 +1,35 @@
...
+
+   // Constants for marking reference id and position as invalid.
+   static const __int32 INVALID_REFID = -1;
+   static const __int32 INVALID_POS = -1;
+};
+//![bedRecord]
+
+int main(){
+	return 0;
+}
```
Comment (h-2) [inline demos/tutorial/bed_io/base.cpp]: newline at EOF missing

File: demos/tutorial/generic_programming/example_hashing.cpp [hunk 7]
```diff
@@ -0,0 +1,83 @@
+#include <seqan/basic.h>
+#include <seqan/sequence.h>
+
+using namespace seqan;
+
+//![hashAll]
+template <typename TShape, typename TString> 
+void hashAll(TShape & shape, TString & str){ 
+    typedef typename Iterator<TString>::Type TIterator;
```
Comment (h-2) [inline demos/tutorial/generic_programming/example_hashing.cpp]: { not at beginning of line

File: demos/tutorial/generic_programming/example_hashing.cpp [hunk 8]
```diff
@@ -0,0 +1,83 @@
...
+    TIterator it = begin(str);
+    TIterator it_end = end(str) - span(shape);
+    while (it != it_end) {
+        unsigned int hash_value = hash(shape, it);
```
Comment (h-2) [inline demos/tutorial/generic_programming/example_hashing.cpp]: { not at beginning of line

File: demos/tutorial/generic_programming/example_hashing.cpp [hunk 9]
```diff
@@ -0,0 +1,83 @@
...
+  public:
+     static unsigned int const span = q;
+};
+//![classUngappedShape]
+
+//![hashNext]
+template <typename TValue, unsigned int q, typename TIterator>
+inline unsigned int
+hashNext(Shape< TValue, UngappedShape<q> > const & shape, TIterator it, unsigned int prev){
+    unsigned int val = prev * ValueSize<TValue>::VALUE - *it * shape.fac
```
Comment (h-2) [inline demos/tutorial/generic_programming/example_hashing.cpp]: { not at beginning of line

File: demos/tutorial/generic_programming/example_hashing.cpp [hunk 10]
```diff
@@ -0,0 +1,83 @@
...
+                            + *(it + shape.span);
+    return val;
+// shape.fac stores |Σ|^q
+}
+//![hashNext]
+
+//![specializedHashAll]
+template <typename TValue, unsigned int q, typename TString>
+void specializedHashAll(Shape< TValue, UngappedShape<q> > & shape, TString & str){
+    typedef typename Iterator<TString>::Type TIterator;
```
Comment (h-2) [inline demos/tutorial/generic_programming/example_hashing.cpp]: { not at beginning of line

File: demos/tutorial/generic_programming/example_hashing.cpp [hunk 11]
```diff
@@ -0,0 +1,83 @@
...
+    TIterator it = begin(str); TIterator it_end = end(str) - span(shape);
+    unsigned int hash_value = hash(shape, it);
+    /* do some things with the hash value */
+
+//![specializedHashAll]
+    ignoreUnusedVariableWarning(hash_value);
+//![specializedHashAll]
+    while (++it != it_end) {
+        unsigned int hash_value = hashNext(shape, it, hash_value);
```
Comment (h-2) [inline demos/tutorial/generic_programming/example_hashing.cpp]: { not at beginning of line

File: demos/tutorial/graph/graph_algo_scc.cpp [hunk 12]
```diff
@@ -19,6 +20,7 @@ int main()
     addEdges(g, edges, numEdges);
     std::cout << g << std::endl;
 //![main-graph-construction]
+std::cout << "//![main-graph-construction]" << std::endl;
```
Comment (h-2) [inline demos/tutorial/graph/graph_algo_scc.cpp]: all couts wrongly indented in this fle

File: demos/tutorial/graph/graph_dijkstra.cpp [hunk 13]
```diff
@@ -55,6 +59,7 @@ int main()
     assignProperty(cityNames, vertHannover, "Hannover");
 //![enter-properties]
 
+std::cout << "//![iterate-and-output-properties]\n";
 //![iterate-and-output-properties]
```
Comment (h-2) [inline demos/tutorial/graph/graph_dijkstra.cpp]: cout wrongly indented

File: demos/tutorial/graph/graph_hmm.cpp [hunk 14]
```diff
@@ -89,7 +92,9 @@ int main()
     }
     std::cout << std::endl;
 //![viterbi]
```
Comment (h-2) [inline demos/tutorial/graph/graph_hmm.cpp]: all couts wrongly indented in this fle

File: demos/tutorial/graph/graph_hmm.cpp [hunk 15]
```diff
@@ -64,10 +64,13 @@ int main()
...
 //![transitions]
 
+std::cout << "//![print-model]" << std::endl;
 //![print-model]
     std::cout << hmm << std::endl;
 //![print-model]
+std::cout << "//![print-model]" << std::endl;
 
+std::cout << "//![viterbi]" << std::endl;
 //![viterbi]
```
Comment (h-2) [inline demos/tutorial/graph/graph_hmm.cpp]: all couts wrongly indented in this fle

File: demos/tutorial/iterators/assignment_3_workshop.cpp [hunk 16]
```diff
@@ -0,0 +1,73 @@
...
+
+using namespace seqan;
+// Function to print simple alignment between two sequences with the same length
+template <typename TText1, typename TText2>
+void printAlign(TText1 const & genomeFragment, TText2 const & read)
+{
+        std::cout <<  "Alignment " << std::endl;
+        std::cout << "  genome : " << genomeFragment << std::endl;
+        std::cout << "  read   : " << read << std::endl;
+}
```
Comment (h-2) [inline demos/tutorial/iterators/assignment_3_workshop.cpp]: four space indention instead of 8/tab

File: demos/tutorial/iterators/base.cpp [hunk 17]
```diff
@@ -0,0 +1,29 @@
...
+    Iterator<DnaString>::Type           it1;  // A standard iterator
+    Iterator<DnaString, Standard>::Type it2;  // Same as above
+    Iterator<DnaString, Rooted>::Type   it3;  // A rooted iterator
+//![construction]
+    ignoreUnusedVariableWarning(it1);
+    ignoreUnusedVariableWarning(it2);
+    ignoreUnusedVariableWarning(it3);
+
+std::cout << "\n//![use-case]\n";
+//![use-case]
```
Comment (h-2) [inline demos/tutorial/iterators/base.cpp]: couts wrongly indented

File: demos/tutorial/modifiers/modreverse.cpp [hunk 18]
```diff
@@ -14,14 +13,21 @@ int main()
     ModifiedString<String<char>, ModReverse> myModifier(myString);
 //![modifier]
 
+std::cout << "//![output1]\n";
 //![output1]
     std::cout << myString << std::endl;
     std::cout << myModifier << std::endl;
```
Comment (h-2) [inline demos/tutorial/modifiers/modreverse.cpp]: couts wrongly indented

File: demos/tutorial/modifiers/nested.cpp [hunk 19]
```diff
@@ -0,0 +1,41 @@
...
+//![reverse]
+    typedef ModifiedString<TMyComplement, ModReverse> TMyReverseComplement;
+//![reverse]
+
+///A reverse complemented string.
+//![constructor]
+    TMyReverseComplement myReverseComplement(myString);
+//![constructor]
+std::cout << "//![output]" << '\n';
+//![output]
```
Comment (h-2) [inline demos/tutorial/modifiers/nested.cpp]: couts wrongly indented

File: demos/tutorial/sequences/assignment_3.cpp [hunk 20]
```diff
@@ -0,0 +1,18 @@
...
+using namespace seqan;
+
+int main()
+{
+    String<Dna5> nucleotides = "AGTCGTGNNANCT";
+    String<Dna5> selected;
+    // Append all elements of nucleotides, apart of Gs,
+    // to the list selected.
+    for (unsigned i = 0; i < length(nucleotides); ++i){
+        appendValue(selected, nucleotides[i]);
```
Comment (h-2) [inline demos/tutorial/sequences/assignment_3.cpp]: { not at line beginning

File: demos/tutorial/string_sets/example_functionality_2.cpp [hunk 21]
```diff
@@ -0,0 +1,43 @@
...
+    DnaString str0 = "TATA";
+    DnaString str1 = "CGCG";
+    appendValue(stringSet, str0);
+    appendValue(stringSet, str1);
+
+    // Get the corresponding ids
+    unsigned id0 = positionToId(stringSet, 0);
+    unsigned id1 = positionToId(stringSet, 1);
+std::cout << "//![main]" << '\n';
+//![main]
```
Comment (h-2) [inline demos/tutorial/string_sets/example_functionality_2.cpp]: couts wrongly indented in this file

File: demos/tutorial/string_sets/example_iterators.cpp [hunk 22]
```diff
@@ -0,0 +1,40 @@
...
+int main()
+{
+    StringSet<DnaString> stringSet;
+    DnaString str0 = "TATA";
+    DnaString str1 = "CGCG";
+    appendValue(stringSet, str0);
+    appendValue(stringSet, str1);
+
+std::cout << "//![simple_example]" << '\n';
+//![simple_example]
```
Comment (h-2) [inline demos/tutorial/string_sets/example_iterators.cpp]: same here

File: demos/tutorial/bed_io/base.cpp [hunk 23]
```diff
@@ -0,0 +1,35 @@
...
+   CharString data;    // any data not fitting into other members
+
+   // Constants for marking reference id and position as invalid.
+   static const __int32 INVALID_REFID = -1;
+   static const __int32 INVALID_POS = -1;
+};
+//![bedRecord]
+
+int main(){
+	return 0;
```
Comment (h-2) [inline demos/tutorial/bed_io/base.cpp]: { into newline
