### PR TITLE
Fix/partial sum serial implementation

### LINKED ISSUE #2093: Timeouts for test_index_bifm
There's a bug when compiled with OpenMP (and gcc). I narrowed it down to the method

`partialSum()` in `parallel/parallel_algorithms.h` which is used for creating the Count table used for the LF mapping. For some reason the program spends > 400s in `do_spin`.

Anyway, there shouldn't be done any parallelization at all (when called by the FMindex). We usually never build indices on alphabet sizes larger than 10 (which will lead to 9 summations).

### PR DESCRIPTION
**Pull request by cpockrandt**
Fixes #2093

### CODE REVIEW

**Comment by h-2** [comment]
indexBiFM still timeouts on travis...

**Comment by cpockrandt** [comment]
I know ... but even when I remove parallelization from the reverse function, there is still parallelization going on that I couldn't locate yet ...

**Comment by h-2** [comment]
what is the state of this?

File: include/seqan/parallel/parallel_algorithms.h [hunk 1]
```diff
@@ -140,9 +140,9 @@ sum(TSequence const &seq)
  * @see sum
  */
 
-template <typename TTarget, typename TSource, typename TParallelTag>
+template <typename TTarget, typename TSource>
 inline typename Value<TSource>::Type
-partialSum(TTarget &target, TSource const &source, Tag<TParallelTag> parallelTag)
+partialSum(TTarget &target, TSource const &source, Parallel)
```
Comment (rrahn) [inline include/seqan/parallel/parallel_algorithms.h]: These changes would break the Serial implementation wouldn't they?
The thing is that the Splitter with the Serial tag would simply make it a single chunk leading to a sequential execution of the following for-loops. So that should not changed.

File: include/seqan/parallel/parallel_algorithms.h [hunk 2]
```diff
@@ -189,6 +189,30 @@ partialSum(TTarget &target, TSource const &source, Tag<TParallelTag> parallelTag
...
+   TIterator dstIt = begin(target, Standard());
+   TValue sum = 0;
+   for (; it != end(source, Standard()); ++it, ++dstIt)
+   {
+       sum += *it;
+       *dstIt = sum;
+   }
+
+   return back(target);
+}
```
Comment (rrahn) [inline include/seqan/parallel/parallel_algorithms.h]: Not necessary if you revert the changes above.

File: include/seqan/modifier/modifier_reverse.h [hunk 3]
```diff
@@ -595,7 +595,7 @@ template < typename TText >
 inline SEQAN_FUNC_DISABLE_IF(Is<StlContainerConcept<TText> >)
 reverse(TText & text)
 {
-    reverse(text, Parallel());
+    reverse(text, Serial());
```
Comment (rrahn) [inline include/seqan/modifier/modifier_reverse.h]: Are you sure about these changes?

**Comment by rrahn** [comment]
@cpockrandt ping

**Comment by cpockrandt** [comment]
I started looking into this issue again. Still working on it but it seems that the generic `partialSum` implementation does not work efficiently in serial mode. I separated the Serial implementation into its own method which increased the running time significantly. This is only true for debug mode though, not if the code is optimized. Probably because for a for-loop with one iteration (one job), a separate thread is spawned each time which is avoided with optimization on.

Afaik the nightly tests are built in debug mode. But there's still a significant time difference. I guess it's time same problem as above but I didn't identify the code part yet.

**Comment by cpockrandt** [comment]
In other words: even though `partialSum` is called in serial mode which will set the number of jobs to 1, it is significantly slower than simply removing the OpenMP macro in [line 174](https://github.com/cpockrandt/seqan/blob/7d7f556597cf8b1a71718c2b96383a2a9b8a2c85/include/seqan/parallel/parallel_algorithms.h#L174)

@rrahn What are your thoughts? Shall I make separate serial implementations like in the first commit?

**Comment by rrahn** [comment]
Mhmm, have you tried restricting the number of threads of the for loop to the length of the splitter?
And no, we run the nightlies in optimised mode but with assertions enabled.

**Comment by cpockrandt** [comment]
Thanks, great idea! That worked 😃 

Unfortunately I didn't identify the other bottlenecks yet.

**Comment by cpockrandt** [comment]
Parallelization problems are fixed now. I also reduced the test case.
