### PR TITLE
[FIXES-#2026] Fixes gnk ctd problems.

### LINKED ISSUE #2026: CTD support broken by new function _typeToString
GenericKnimeNodes expects `int` instead of `integer`as a type. When we replaced the hardcoded types [here](https://github.com/seqan/seqan/blob/966da62f2ba61867359cad18f4db2dbaf431243e/include/seqan/arg_parse/arg_parse_ctd_support.h#L394) with _typeToString() the `int` was replaced by `integer` ([here](https://github.com/seqan/seqan/blob/966da62f2ba61867359cad18f4db2dbaf431243e/include/seqan/arg_parse/arg_parse_argument.h#L234) )

This causes a failure in generating KNIME nodes. 

And one more thing 
`version-check` parameter has a `bool` type but the restrictions are `1,ON,TRUE,T,YES,0,OFF,FALSE,F,NO`.

This is also causing a problem. We either have to make it a `string` type or restrict the "restrictions" to TRUE and FALSE. (See [`getRestrictions`](https://github.com/seqan/seqan/blob/966da62f2ba61867359cad18f4db2dbaf431243e/include/seqan/arg_parse/arg_parse_ctd_support.h#L164) )

### PR DESCRIPTION
**Pull request by rrahn**
fixes #2026

### CODE REVIEW

File: include/seqan/arg_parse/arg_parse_ctd_support.h [hunk 1]
```diff
@@ -281,6 +289,17 @@ inline std::string _getManual(ArgumentParser const & me)
 }
 
 // ----------------------------------------------------------------------------
+// Function _toValidGnkTypeSpecifier()
+// ----------------------------------------------------------------------------
+
+inline std::string _toValidGnkTypeSpecifier(std::string type)
```
Comment (h-2) [inline include/seqan/arg_parse/arg_parse_ctd_support.h]: please don't copy, even if it's not performance sensitive code :nail_care:
