### PR TITLE
[FIX] Alignment: Fixing MyersHirschberg implementation.

### LINKED ISSUE #1711: Segfault and assert fail when calculating alignment using MyersHirschberg method
Hi Seqan team! First of all, I really like your library - great documentation and easy to use.

I am an author of https://github.com/Martinsos/edlib - library that implements Myers+Hirschberg algorithm in order to calculate Levenshtein distance and find alignment of two sequences. I am trying to compare Edlib with Seqan's implementation of Myers+Hirschberg and pairwise alignment in general, however Seqan's finding of alignment in most cases fails with error - I would appreciate any help on this!

I do initialization like this:
```
TSequence querySeqAn;
for (int idx = 0; idx < querySize; idx++) {
    seqan::appendValue(querySeqAn, query[idx]);  // query is array of unsigned char.
}
TSequence targetSeqAn;
for (int idx = 0; idx < targetSize; idx++) {
    seqan::appendValue(targetSeqAn, target[idx]);  // target is array of unsigned char.
}
TAlign align;
seqan::resize(seqan::rows(align), 2);
seqan::assignSource(seqan::row(align, 0), targetSeqAn);
seqan::assignSource(seqan::row(align, 1), querySeqAn);
```

I am working with genome data, so alphabet is ACTG.

When I search just for score, it is all fine:
```
score = seqan::globalAlignmentScore(querySeqAn, targetSeqAn, seqan::MyersBitVector());
```
works fine.
```
score = seqan::globalAlignmentScore(targetSeqAn, querySeqAn,
                                                        seqan::Score<int, seqan::Simple>(0, -1, -1),
                                                        seqan::AlignConfig<true, false, false, true>(),
                                                        seqan::LinearGaps());
```
also works fine.

However, when I search for alignment like this:
a)
```
int score = seqan::globalAlignment(align, seqan::MyersHirschberg());
```
or like this:
b)
```
score = seqan::globalAlignment(align, seqan::Score<int, seqan::Simple>(0, -1, -1),
                                                   seqan::AlignConfig<true, false, false, true>(),
                                                   seqan::LinearGaps());
```
I get errors!

It does work for some basic, short dummy sequences, but it fails for almost all of the large ones (>15kbp). Errors are sometimes segfault, sometimes it is assert, and sometimes it is something else. They usually do not happen immediately, but after seqan has been running for some itme.

Some examples of error:
1. when comparing two sequences where each has size of about 100k and using code under a), I got `munmap_chunk(): invalid pointer.`
2. when comparing two seqs where first is 1kbp and another is 5000kbp using code b), I got `malloc.c:3723: _int_malloc: Assertion (unsigned long) (size) >= (unsigned long) (nb)' failed.`

Am I doing something wrong on my side, or is there some limit on size of the sequences? Thank you for any help!

### PR DESCRIPTION
**Pull request by rrahn**
Hopefully fixes #1711.
I could not reproduce the same error, but I found some general issues with the current code.

1. Removed all constructors and assignment operator from ```HirschbergSet_``` and let compiler generate them.
2. Resetting the vectors ```VP``` and ```VN``` was ill formed and exceeded the vector boundaries.

### CODE REVIEW

File: include/seqan/align/global_alignment_hirschberg_impl.h [hunk 1]
```diff
@@ -101,13 +81,13 @@ class HirschbergSet_
 // Function _begin1()
 // ----------------------------------------------------------------------------
 
-inline int&
+inline unsigned&
```
Comment (h-2) [inline include/seqan/align/global_alignment_hirschberg_impl.h]: space between unsigned and &

File: include/seqan/align/global_alignment_hirschberg_impl.h [hunk 2]
```diff
@@ -701,8 +681,8 @@ _globalAlignment(Gaps<TSequenceH, TGapsSpecH> & gapsH,
             std::cout << "requested position in c_score and pointer is " << _end2(target) << std::endl;
             std::cout << "alignment score is " << c_score[_end2(target)] << std::endl << std::endl;
 #endif
-            to_process.push(HirschbergSet_(mid,_end1(target),pointer[_end2(target)],_end2(target),0));
-            to_process.push(HirschbergSet_(_begin1(target),mid,_begin2(target),pointer[_end2(target)],0));
+            to_process.push(HirschbergSet_ { mid, _end1(target), pointer[_end2(target)], _end2(target), 0});
```
Comment (h-2) [inline include/seqan/align/global_alignment_hirschberg_impl.h]: no space between { and mid

File: include/seqan/align/global_alignment_myers_hirschberg_impl.h [hunk 3]
```diff
@@ -167,6 +167,21 @@ namespace seqan {
 // Function globalAlignment()
 // ----------------------------------------------------------------------------
 
+template <typename TStream, typename T>
+inline void
+_printBinary(TStream & stream, T const n)
```
Comment (h-2) [inline include/seqan/align/global_alignment_myers_hirschberg_impl.h]: whats this?

File: include/seqan/align/global_alignment_myers_hirschberg_impl.h [hunk 4]
```diff
@@ -254,7 +269,7 @@ _globalAlignment(Gaps<TSequenceH, TGapsSpecH> & gapsH,
         reverseBitMask[blockCount * ordValue(getValue(y,len_y - j - 1)) + j/BLOCK_SIZE] = reverseBitMask[blockCount * ordValue(getValue(y,len_y - j - 1)) + j/BLOCK_SIZE] | 1 << (j%BLOCK_SIZE);
     }
 
-    HirschbergSet_ hs_complete(0,len_x,0,len_y,1);
+    HirschbergSet_ hs_complete {0, static_cast<unsigned>(len_x), 0, static_cast<unsigned>(len_y), 1};
```
Comment (h-2) [inline include/seqan/align/global_alignment_myers_hirschberg_impl.h]: no spaces before `{` either

File: include/seqan/align/global_alignment_myers_hirschberg_impl.h [hunk 5]
```diff
@@ -735,8 +746,8 @@ _globalAlignment(Gaps<TSequenceH, TGapsSpecH> & gapsH,
             printf("Optimal cut is at %i and %i with forward score %i and reverse score %i\n\n",mid,pos_max,(max - rmax),rmax);
 #endif
             /* push the two computed parts of the dp-matrix on process stack */
-            to_process.push(HirschbergSet_(pos_max,_end1(target),mid,_end2(target),rmax));
-            to_process.push(HirschbergSet_(_begin1(target),pos_max,_begin2(target),mid,max - rmax));
+            to_process.push(HirschbergSet_ {pos_max, _end1(target), mid, _end2(target), rmax});
```
Comment (h-2) [inline include/seqan/align/global_alignment_myers_hirschberg_impl.h]: no spaces before `{` either

File: include/seqan/align/global_alignment_myers_hirschberg_impl.h (hunk 3 above)
Comment (rrahn) [inline include/seqan/align/global_alignment_myers_hirschberg_impl.h]: helper funciton.
