### PR TITLE
[FIXES-#2245] prevent wrong over/underflow on platforms where char is unsigned

### LINKED ISSUE #2245: New platform issues
:sob: 

https://buildd.debian.org/status/package.php?p=seqan2&suite=experimental

- [x] test_align_parallel_data_structures [ppc64el]
- [x] test_demo_tutorial_file_io_overview_solution3 [ppc64el, arm64, s390x, powerpc, ppc64]
- [x] test_demo_tutorial_sam_and_bam_io_example7 [ppc64el, arm64, s390x, powerpc, ppc64]
-  ~~enable UME simd in nightly builds on larix.~~

@rrahn can you look at the first one, I will have a look at the other two.

### PR DESCRIPTION
**Pull request by h-2**
fixes #2245

### CODE REVIEW

File: include/seqan/bam_io/read_bam.h [hunk 1]
```diff
@@ -267,7 +267,7 @@ readRecord(BamAlignmentRecord & record,
     TQualIter qitEnd = end(record.qual, Standard());
     for (TQualIter qit = begin(record.qual, Standard()); qit != qitEnd;)
         *qit++ = '!' + *it++;
-    if (!empty(record.qual) && (record.qual[0] - '!') == '\xff')
+    if (!empty(record.qual) && char(record.qual[0] - '!') == '\xff')
```
Comment (rrahn) [inline include/seqan/bam_io/read_bam.h]: Is `static_cast` not working here?

Comment (h-2) [reply include/seqan/bam_io/read_bam.h]: It works, but it is more verbose and less explicit IMHO.
