### PR TITLE
[INTERNAL, FIX-#699] Add check for possible score overflow in banded chain alignment

### LINKED ISSUE #699: Fatal Error in Banded Chain Alignment Traceback
The traceback computation of the banded chain alignment crashes with an assertion. 
See error log by Brett Bowman.
```
bbowman@localhost:~/git/SRSLI$ ./src/C++/srsli test/data/query/ecoli_5p_sample.fastq test/data/reference/ecoliK12_5p_assembly.fasta 
Query 0
Finished finding seeds
Finishing chaining seeds
Starting alignment of sequences
/usr/include/seqan/seeds/banded_chain_alignment_traceback.h:195 Assertion failed : isGlued == true was: 0 != 1 (Fatal error while trying to connect trace backs: No glue point available!)
Aborted (core dumped)
```

### PR DESCRIPTION
**Pull request by rrahn**
Checks if a score overflow is likely for a given alignment sub matrix in the banded chain alignment procedure.

Fixes #699.

### CODE REVIEW

**Comment by h-2** [comment]
@rrahn please do not rename the member variables just for the fun of it :sleepy:

**Comment by rrahn** [comment]
It's not for the fun of it, but to use the global scoreMatch and scoreMismatch function on that score object. But I agree at least the other variables need to be renamed in the same scheme.

**Comment by rrahn** [comment]
Ok, I reverted the renaming. Apparently, there where already setter and getter functions but not complete.

File: include/seqan/journaled_set/score_biaffine.h [hunk 1]
```diff
@@ -90,13 +90,6 @@ class Score<TScoreValue, BiAffine>
...
                                                                         _gapExtendVertical(gapExtendVertical),
                                                                         _gapOpenVertical(gapOpenVertical) {}
-
-    Score(Score const & other) : _match(other._match),
-                                 _mismatch(other._mismatch),
-                                 _gapExtendHorizontal(other._gapExtendHorizontal),
-                                 _gapOpenHorizontal(other._gapOpenHorizontal),
-                                 _gapExtendVertical(other._gapExtendVertical),
-                                 _gapOpenVertical(other._gapOpenVertical) {}
 };
```
Comment (h-2) [inline include/seqan/journaled_set/score_biaffine.h]: Why was this removed?

Comment (h-2) [inline include/seqan/journaled_set/score_biaffine.h]: I think there definitely should be a copy constructor, but it could also be defaulted. TBH, if you change this you could as well make it an aggregate type and remove all the constructors. But this require changes in other places...

Comment (rrahn) [inline include/seqan/journaled_set/score_biaffine.h]: No, the copy constructor will be defaulted since the custom constructs won't affect this.
Otherwise rule-of-5- applies 😫. Probably the best would be aggregate type, but then it is not consistent with other score types and I don't see the point of changing all this for this small class, which is used in only one place at the moment. The other constructors are for consistency with the Simple score class.
