### PR TITLE
fix URIEncoding problem for entities with ::

### LINKED ISSUE #831: The escaping of html file names in the dox system seems to be odd
For example see ```FragmentStore::PredefinedAnnotationTypes```, where the frame-based link does not point to the correct address (when searching with ```?p=FragmentStore::PredefinedAnnotationTypes```).

The problem occurs, when the ```::``` in the name is converted in the ```write_html.py``` to some own encoding theme. Within ```common.js```, the URI is encoded using ```encodingURIComponent``` leading to a different sequence name. Moreover the script cuts of the part before the colons and directs it to the ```FragmentStore.html```, which is not the linked site to be displayed.

This needs some more thoughts and it would be sufficient to fix it after 2.0.0.
@holtgrewe @bkahlert Your insights to this would be nice!

### PR DESCRIPTION
**Pull request by xenigmax**
This will fix #831 .

Check how it works : 
http://docs.seqan.de/seqan/master_version_test_832/?p=FragmentStore::PredefinedAnnotationTypes

### CODE REVIEW

File: util/py_lib/seqan/dox/tpl/js/common.js [hunk 1]
```diff
@@ -35,7 +35,11 @@
                         hash = '::' + tmp.split('::')[1];
                         console.log('p == ' + p + ' -- hash = ' + hash);
                     }
-                    if(window.lookup.hasOwnProperty(p)) {
+
```
Comment (rrahn) [inline util/py_lib/seqan/dox/tpl/js/common.js]: Please remove the empty line.

**Comment by rrahn** [comment]
LGTM just the minor nail polishing thing and I'll merge.
