### PR TITLE
Fix/finder disallow non containerconcepts

### LINKED ISSUE #1683: Finder on an index sometimes allows to search Dna5 and sometimes not.
This code snippet works:

``` c++
Dna5String genome = "ACGTGCTAGCGATGACGATGCAGACTGACTGGACAGGCATGA";

Index<Dna5String, IndexEsa<> > index(genome);
Finder<Index<Dna5String, IndexEsa<> > > finder(index);
Dna5 needle(0);
find(finder, needle);
```

This doesn't:

``` c++
Dna5String genome = "ACGTGCTAGCGATGACGATGCAGACTGACTGGACAGGCATGA";

Index<Dna5String, FMIndex<> > index(genome);
Finder<Index<Dna5String, FMIndex<> > > finder(index);
Dna5 needle(0);
find(finder, needle);
```

I know that `needle` should be `Dna5String needle = "A"`. But I think it should be either allowed or disallowed in both cases.

### PR DESCRIPTION
**Pull request by cpockrandt**
Resolves #1683

### CODE REVIEW

File: tests/index/test_index_finder.cpp [hunk 1]
```diff
@@ -72,7 +72,7 @@ SEQAN_TYPED_TEST_CASE(IndexFinderTest, UnidirectionalIndexTypes);
 SEQAN_TYPED_TEST(IndexFinderTest, FindFirstChar)
 {
     SEQAN_ASSERT(find(this->finder, prefix(concat(this->text), 1u)));
-    SEQAN_ASSERT(find(this->finder, (const char*)"A"));
+    SEQAN_ASSERT(find(this->finder, "A"));
```
Comment (h-2) [inline tests/index/test_index_finder.cpp]: shouldn't an array of length one still be containerconcept? I though only `'A'` wouldn't be...

Comment (cpockrandt) [inline tests/index/test_index_finder.cpp]: I didn't notice the asterix :grin:

@h-2 Should I simply allow ``TPattern`` to be a pointer in ``find()``? Because `(const char*)` didn't implement the ContainerConcept.

**Comment by h-2** [comment]
@cpockrandt ping, can you reply to the question?
